name: Lint

on: [push,pull_request,workflow_dispatch]

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  pull-requests: read
  checks: write
  issues: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Tests
        run: |
          go test $(go list ./...)

      - name: Commit back
        if: ${{ !github.event.pull_request }}
        continue-on-error: true
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "ci(chore): Fix stylings"
          git push

      - name: Suggester
        if: ${{ github.event.pull_request }}
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: golangci-lint
